### ISSUE TITLE
Mangekyou Sharingan

### ISSUE THREAD

**Issue by thehavre** [Fury-2K/Sharingan-Loader#3]
Thanks for such an awesome HUD!
It works and looks great 👍 

Is it possible to add the Mangekyou Sharingan feature? For example, for some long-term tasks like file downloading this simple sharingan may transform to the Mangekyou Sharingan!

Just imagine like user with really poor network connection is waiting while its favourite Naruto episode is downloading, it's pity. But suddenly Mangekyou Sharingan appears and now user is cheered up 😉

**Comment by Fury-2K** [comment]
Thanks for the feedback. I have added the mangekyou sharingan as well. You can share images for other eyes if you want more. :) more customization will be added in future updates.

**Comment by thehavre** [comment]
Arigato gozaimasu! Will use it :)
